version: '3'
services:
  discord-timecard-2:
    container_name: discord-timecard-2
    image: ghcr.io/discord-iamtakagi-net/discord-timecard-2:master
    volumes:
      - ./config.yml:/config.yml
    env_file:
      - .env